
# Examaple of child image where you add your own config/ directory
# You could override the run script here if you wanted
# An alternative is to mount config as a directory
FROM forgerock/openam:latest


ADD config/ /var/tmp/config
