#!/usr/bin/env bash

# create the skeleton directory - so copying in keystore works on boot
mkdir -p /root/openam/openam

if [ -d /var/secrets/openam ]; then
   echo "secret volume mounted - will copy secrets"
   cp -f  /var/secrets/openam/{.keypass,.storepass,keystore.jceks,keystore.jks} /root/openam 2>/dev/null
fi


if [ ! -d "$HOME/.openamcfg" ]; then
   echo "Recreating .openamcfg "
   mkdir -p "$HOME/.openamcfg"
   echo "/root/openam"  >  "$HOME/.openamcfg/AMConfig_usr_local_tomcat_webapps_openam_"
fi


exec /usr/local/tomcat/bin/catalina.sh run